### PR TITLE
Implements #242, styling of received likes count.

### PR DESCRIPTION
**Pull request by lairdshaw**
Doesn't implement the table of likes which @Eldenroot suggested in a comment in that issue - that should probably be opened as a separate issue.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Great! Pleae could you provide any screenshots or how we can change color?
Moreover please share you ideas, I am quite interested :-!

Dne so 3. říj 2020 21:29 uživatel Laird <notifications@github.com> napsal:

**Comment by lairdshaw** [comment]
> Great! Pleae could you provide any screenshots or how we can change color?

Let's take your list from issue #242:

- 0 = grey
- 1-10 = yellow
- 10-50 = orange [I assume you meant 11, not 10, here --Laird]
- 51-150 = green [I assume you simply meant >=51 here, since that's how the new setting handles the last interval --Laird]

To implement this, we would set the value of the new "Received likes styling ranges" setting to "0,1,11,51".

Then we would edit the thankyoulike.css stylesheet in our theme, first deleting the default styling:

```css
.tyl_rcvdlikesrange_1{
	font-weight: bold;
	color: green;
}
```

And then adding this styling to it:

```css
.tyl_rcvdlikesrange_1{
	color: grey;
}
.tyl_rcvdlikesrange_2{
	color: yellow;
}
.tyl_rcvdlikesrange_3{
	color: orange;
}
.tyl_rcvdlikesrange_4{
	color: green;
}
```

Makes sense?

> Moreover please share you ideas, I am quite interested :-!

Unfortunately, they're nothing exciting, just minor fixes to the code:

- Move the creation of the Master stylesheet from installation to activation (with reasoning per [this thread](https://community.mybb.com/thread-229632.html) I've just started on the community forums).
- Eliminate duplicated code in thankyoulike.php and inc/plugins/thankyoulike.php, especially the code to generate the list of likers at the bottom of a post.
- Don't hard-code commas for the `$comma` variable; instead, retrieve them from `$lang->comma`.
- Possibly a few others that I've temporarily forgotten.

**Comment by Eldenroot** [comment]
Oh, great, now I understand. Great I really like it!

About the mentioned improvements, do you plan to add them into this release
or do we add them to the next one?

Dne so 3. říj 2020 22:01 uživatel Laird <notifications@github.com> napsal:

**Comment by lairdshaw** [comment]
> About the mentioned improvements, do you plan to add them into this release or do we add them to the next one?

Let's add them to this release. I'll try to implement them soon - probably in the next few hours. I don't think I'll get the table of likes done for this release though.

**Comment by Eldenroot** [comment]
Ok, I agree! Good job buddy.

We should clean up the issue list here on Github, some tickets are not relevant or I think not worth to add.

**Pull request merged**
