### PR TITLE
Fix #244: statistics breakdown on member profile

### LINKED ISSUE #244: List of thank you/likes with basic statistics (based on MyBB reputation feature)
This was discussed earlier¨- more info here

https://github.com/mybbgroup/Thank-you-like-system/issues/242#issuecomment-700686691

### PR DESCRIPTION
**Pull request by lairdshaw**
Fix #244.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Wow, will try in 10 hours. 

Can you share some screenshot? 

Thank you

**Comment by lairdshaw** [comment]
> Can you share some screenshot?

tyl-member-profile-stats-screenshot

**Comment by Eldenroot** [comment]
Maybe we can make likes given/received clickable with redirect to tyl search?

**Comment by Eldenroot** [comment]
Also we should handle 'deleted member'

If the user is deleted, should we remove all thanks/likes from all posts where had been added or leave them?

**Comment by lairdshaw** [comment]
> Maybe we can make likes given/received clickable with redirect to tyl search?

Do you mean the headings ("Likes received" and "Likes given")?

**Comment by lairdshaw** [comment]
> Also we should handle 'deleted member'
> 
> If the user is deleted, should we remove all thanks/likes from all posts where had been added or leave them?

I'm thinking that we leave them, just like we leave their posts, but I'm open to different opinions.

**Comment by Eldenroot** [comment]
> > Maybe we can make likes given/received clickable with redirect to tyl search?
> 
> Do you mean the headings ("Likes received" and "Likes given")?

Yes, exactly.

Also we should impro the layout a little bit (design). 'There is too many rows (it looks like zebra :)) Maybe we can group the "time period and stats" together, leave same background color. 

For top given/received likes/thx - hmm, we will maybe need same cure. First of all, we need to visually split the "stats for time period" and these two groups of top users :)

I really like it, good work. Thank you buddy!

**Comment by lairdshaw** [comment]
> Maybe we can group the "time period and stats" together, leave same background color.
> 
> For top given/received likes/thx - hmm, we will maybe need same cure. First of all, we need to visually split the "stats for time period" and these two groups of top users :)

Something like this?

tyl-member-profile-stats-screenshot unzebrafied

**Comment by Eldenroot** [comment]
Much better! One more idea - what if we can add "%" calculation for the amount of like/thx for every user? It will be calculated from the total amount of thx/like received (or given) and the result will be placed to the column next to the amount of thx/like from every user.

Also small design changes - "bold" total amount of like/thx in the first part; add Time period to the header?

Bez názvu

**Comment by lairdshaw** [comment]
Happy with the emboldening and percentages. Not so sure we need to add a "Time period" heading as it seems obvious already and adds unnecessary details for the reader to take in, but will go with it if you're dead keen on it. Right now I need to take a rest though - if I fall asleep I'll probably not be back until morning (my timezone; AEST). See you in a bit, buddy.

**Comment by Eldenroot** [comment]
Ok, agree. No time period in the header.

**Comment by lairdshaw** [comment]
Here's what I've got now. Is there anything else or shall I submit a PR?

tyl-member-profile-stats-screenshot with-bold-and-percentages

**Comment by Eldenroot** [comment]
Do we use usergroup's styling for usernames in this list? If yes, then I am fully satisfied! :)

**Comment by lairdshaw** [comment]
> Do we use usergroup's styling for usernames in this list?

Yep.

> If yes, then I am fully satisfied! :)

Excellent. I'll tidy up the code and then push the final commit for this PR.

**Pull request merged**
